apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyqtest
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 45
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hyqtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hyqtest
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: hyqtest
#                    operator: Exists
      containers:
        - image: cr-cn-beijing.volces.com/vke_pre/nginx:1.21.0-debian-10-r0
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30